# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".latexmkrc",
    ".texqc",
    ".texsc",
    "**.json",
    "**.md",
    "**.pdf",
    "**.txt",
    "**/.gitignore",
    "**/.latexmkrc",
    "**/.texqc",
    "**/.texsc",
    "**/*.csv",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.txt",
    "**/*.vm",
    "**/aspell.en.pws",
    "**/DEPENDS.txt",
    "aspell.en.pws",
    "DEPENDS.txt",
    "README.md",
    "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2024-2026 Zerocracy"
SPDX-License-Identifier = "MIT"
