# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: bibcop
'on':
  push:
    paths:
      - '**.bib'
      - '.github/workflows/bibcop.yml'
  pull_request:
jobs:
  bibcop:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: yegor256/bibcop-action@0.0.4
