# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: latexmk
'on':
  push:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  latexmk:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: yegor256/latexmk-action@0.18.0
        with:
          opts: -pdf
          debs: fonts-noto-core fonts-noto-extra fonts-roboto
          depends: DEPENDS.txt
